### PR TITLE
Support for reverse order of caption and figure

### PR DESCRIPTION
**Pull request by camitz**
Using chunk option fig.cap.below_fig = FALSE (default true), caption appears bove figure in output.

### CODE REVIEW

**Comment by camitz** [comment]
I don't know if you like the name of the option, but it works! And quite useful to fulfill particular layout requirements.

**Comment by davidgohel** [comment]
Cool, many thanks. 

I have requests before merging:

* Could you name the option `fig.topcaption`? See https://github.com/yihui/knitr-examples/blob/master/099-include-graphics.Rmd#L62. It will then be the same than `knitr` which is better I think.
* A technical detail, could you instead of `ifelse(options$fig.cap.below_fig...)` use an `if` (`if(options$fig.cap.below_fig...)... else `)?
* Add a note in the doc about this option https://github.com/davidgohel/officedown/blob/master/R/rdocx_document.R#L141

**Comment by camitz** [comment]
Absolutely!

**Comment by davidgohel** [comment]
thanks!

**Comment by camitz** [comment]
@davidgohel Thank you!

**Pull request merged**
